version: "3.9"

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: venda_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: venda_db
      MYSQL_PASSWORD: venda_db123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"

volumes:
  db_data:
